---
# tasks file for zabbix_agent
- name: Checking for Required Variables
  fail: msg="Variable '{{ item }}' is not defined"
  when: "{{ item }} is not defined"
  with_items: "{{ required_vars }}"
 
- name: Configure Zabbix Repo
  yum:
    name: http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
    state: present

- name: Install Zabbix Agent RPMs
  yum:
    name: zabbix-agent, zabbix-sender
    state: present

- name: Update Zabbix Agent conf file
  template:
    src: zabbix_agent.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
    setype: etc_t
  register: updated_zabbix_agent_conf

- name: Is Zabbix Agent running? (Check for possible restart)
  shell: service zabbix-agent status  warn=false
  register: zabbix_agent_running
  ignore_errors: true
  failed_when: falase
  when: updated_zabbix_agent_conf.changed

- name: Stop Zabbix Agent
  service:
    name: zabbix-agent
    state: stopped
  when: updated_zabbix_agent_conf.changed and "zabbix_agent_running.rc == 0"

- name: Start Zabbix Agent
  service:
    name: zabbix-agent
    enabled: true
    state: started

